library(tidyverse)
year <- lag(replication$NEWSPREAD, 12)
year.t <- tail(year, 562)
USREC.y <- tail(replication$USREC, 562)
date.y <- tail(replication$DATE, 562)
date.y <- tail(replication$DATE, 562)
modely <- glm(USREC.y ~ year.t, family = binomial(link="probit"))
summary(modely)
yearz <- predict(modely)
yearp <- pnorm(yearz)
p1 <- ggplot() + geom_line(aes(x=date.y, y=yearp), color="blue")
p1+geom_col(aes(x=date.y, y=USREC.y), alpha=0.3) + xlab("") + ylab("Probability")