library(tidyverse)
library(MASS)
indicators <- read_csv("Data/Aggregated Data/indicatorsfedfunds.csv",col_types = cols(USREC = col_integer(),raDATE = col_date(format = "%Y-%m")))
spread <- lag(indicators$SPREAD, 6)
spread.t <- tail(spread, 777)
USREC.t <- tail(indicators$USREC, 777)
date.t <- tail(indicators$raDATE, 777)
INDPRO <- lag(indicators$INDPRO, 6)
INDPRO.t <- tail(INDPRO, 777)
CPI <- lag(indicators$CPIAUCSL, 6)
CPI.t <- tail(CPI, 777)
FFR <- lag(indicators$FEDFUNDS, 6)
FFR.t <- tail(FFR, 777)
election.t <- tail(election.y, 777)
model <- glm(USREC.t ~ spread.t + FFR.t + CPI.t + INDPRO.t + election.t, family = binomial(link="probit"))
step <- stepAIC(model)
summary(model)
summary(step)
zscores <- predict(model)
probs <- pnorm(zscores)
p1 <- ggplot() + geom_line(aes(x=date.t, y=probs), color="blue")
p1+geom_col(aes(x=date.t, y=USREC.t),alpha=0.3) + xlab("") + ylab("Probability")