library(tidyverse)
indicators <- read_csv("Data/Aggregated Data/indicators.csv",col_types = cols(USREC = col_integer(),raDATE = col_date(format = "%Y-%m")))
threemonth <- lag(indicators$SPREAD, 3)
threemonth.t <- tail(threemonth, 795)
USREC.tm <- tail(indicators$USREC, 795)
date.tm <- tail(indicators$raDATE, 795)
modeltm <- glm(USREC.tm ~ threemonth.t, family = binomial(link="probit"))
summary(modeltm)
threemonthz <- predict(modeltm)
threemonthp <- pnorm(threemonthz)
p1 <- ggplot() + geom_line(aes(x=date.tm, y=threemonthp), color="blue")
p1+geom_col(aes(x=date.tm, y=USREC.tm), alpha=0.3) + xlab("") + ylab("Probability")
