library(tidyverse)
library(MASS)
indicators <- read_csv("Data/Aggregated Data/indicatorsfedfunds.csv",col_types = cols(USREC = col_integer(),raDATE = col_date(format = "%Y-%m")))
spread <- lag(indicators$SPREAD, 3)
spread.t <- tail(spread, 780)
USREC.t <- tail(indicators$USREC, 780)
date.t <- tail(indicators$raDATE, 780)
INDPRO <- lag(indicators$INDPRO, 3)
INDPRO.t <- tail(INDPRO, 780)
CPI <- lag(indicators$CPIAUCSL, 3)
CPI.t <- tail(CPI, 780)
FFR <- lag(indicators$FEDFUNDS, 3)
FFR.t <- tail(FFR, 780)
election.t <- tail(election.y, 780)
model <- glm(USREC.t ~ spread.t + FFR.t + CPI.t + INDPRO.t + election.t, family = binomial(link="probit"))
step <- stepAIC(model)
summary(model)
summary(step)
zscores <- predict(model)
probs <- pnorm(zscores)
p1 <- ggplot() + geom_line(aes(x=date.t, y=probs), color="blue")
p1+geom_col(aes(x=date.t, y=USREC.t),alpha=0.3) + xlab("") + ylab("Probability")