library(tidyverse)
library(MASS)
indicators <- read_csv("Data/Aggregated Data/indicatorsfedfunds.csv", col_types = cols(USREC = col_integer(),raDATE = col_date(format = "%Y-%m")))
spread <- lag(indicators$SPREAD, 24)
spread.t <- tail(spread, 759)
USREC.t <- tail(indicators$USREC, 759)
date.t <- tail(indicators$raDATE, 759)
INDPRO <- lag(indicators$INDPRO, 24)
INDPRO.t <- tail(INDPRO, 759)
CPI <- lag(indicators$CPIAUCSL, 24)
CPI.t <- tail(CPI, 759)
FFR <- lag(indicators$FEDFUNDS, 24)
FFR.t <- tail(FFR, 759)
election.t <- tail(election.y, 759)
model <- glm(USREC.t ~ spread.t + FFR.t + CPI.t + INDPRO.t + election.t, family = binomial(link="probit"))
step <- stepAIC(model)
summary(model)
summary(step)
stepModel <- glm(USREC.t ~ spread.t + CPI.t + INDPRO.t, family = binomial(link="probit"))
zscores <- predict(stepModel)
probs <- pnorm(zscores)
p1 <- ggplot() + geom_line(aes(x=date.t, y=probs), color="blue")
p1+geom_col(aes(x=date.t, y=USREC.t),alpha=0.3) + xlab("")
+ ylab("Probability")