library(tidyverse)
indicators <- read_csv("Data/Aggregated Data/indicatorsfedfunds.csv",col_types = cols(USREC = col_integer(),raDATE = col_date(format = "%Y-%m")))
year <- lag(indicators$SPREAD, 24)
year.t <- tail(year, 759)
USREC.y <- tail(indicators$USREC, 759)
date.y <- tail(indicators$raDATE, 759)
INDPRO.y <- lag(indicators$INDPRO, 24)
INDPRO.y.t <- tail(INDPRO.y, 759)
CPI.y <- lag(indicators$CPIAUCSL, 24)
CPI.y.t <- tail(CPI.y, 759)
FFR.y <- lag(indicators$FEDFUNDS, 24)
FFR.y.t <- tail(FFR.y, 759)
election.y.t <- tail(election.y, 759)
modely <- glm(USREC.y ~ year.t + FFR.y.t + INDPRO.y.t + CPI.y.t + election.y.t, family = binomial(link="probit"))
summary(modely)
yearz <- predict(modely)
yearp <- pnorm(yearz)
p1 <- ggplot() + geom_line(aes(x=date.y, y=yearp), color="blue")
p1+geom_col(aes(x=date.y, y=USREC.y),alpha=0.3) + xlab("") + ylab("Probability")