library(tidyverse)
library(MASS)
indicators <- read_csv("Data/Aggregated Data/indicatorsfedfunds.csv",col_types = cols(USREC = col_integer(),raDATE = col_date(format = "%Y-%m")))
spread <- lag(indicators$SPREAD, 12)
spread.t <- tail(spread, 771)
USREC.t <- tail(indicators$USREC, 771)
date.t <- tail(indicators$raDATE, 771)
INDPRO <- lag(indicators$INDPRO, 12)
INDPRO.t <- tail(INDPRO, 771)
CPI <- lag(indicators$CPIAUCSL, 12)
CPI.t <- tail(CPI, 771)
FFR <- lag(indicators$FEDFUNDS, 12)
FFR.t <- tail(FFR, 771)
election.t <- tail(election.y, 771)
model <- glm(USREC.t ~ spread.t + FFR.t + CPI.t + INDPRO.t + election.y.t, family = binomial(link="probit"))
step <- stepAIC(model)
summary(model)
summary(step)
zscores <- predict(model)
probs <- pnorm(zscores)
p1 <- ggplot() + geom_line(aes(x=date.t, y=probs), color="blue")
p1+geom_col(aes(x=date.t, y=USREC.t),alpha=0.3) + xlab("") + ylab("Probability")