library(tidyverse)
indicators <- read_csv("Data/Aggregated Data/indicators.csv",col_types = cols(USREC = col_integer(),raDATE = col_date(format = "%Y-%m")))
year <- lag(indicators$SPREAD, 12)
year.t <- tail(year, 786)
USREC.y <- tail(indicators$USREC, 786)
date.y <- tail(indicators$raDATE, 786)
modely <- glm(USREC.y ~ year.t, family = binomial(link="probit"))
summary(modely)
yearz <- predict(modely)
yearp <- pnorm(yearz)
p1 <- ggplot() + geom_line(aes(x=date.y, y=yearp), color="blue")
p1+geom_col(aes(x=date.y, y=USREC.y),alpha=0.3) + xlab("") + ylab("Probability")